import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${plusJakarta.className} antialiased`}>
        <div className="relative flex min-h-screen bg-[#F2F7FF]">
          <Sidebar className="absolute top-32 left-0 z-50" />
          <main className="flex-1 p-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
//F2F7FF
//EDF2FB
